namespace: romank8k
name: developer
version: 1.0.0
readme: README.md

authors:
  - Roman Khmelichek

description: Building blocks used to construct playbooks to automate creation of development environments.

license:
  - MIT

tags: []

dependencies:
  community.general: ">=8.4.0"

repository: https://github.com/romank8k/ansible-collection-developer
documentation: https://github.com/romank8k/ansible-collection-developer
homepage: https://github.com/romank8k/ansible-collection-developer
issues: https://github.com/romank8k/ansible-collection-developer/issues

build_ignore:
  - .gitignore
  - .idea
